/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazarq;

import ObjetoNegocio.Cañas;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.net.URI;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;
import org.greenrobot.eventbus.EventBus;

/**
 *
 * @author Manuel
 */
public class Frm_MenuPrincipal extends javax.swing.JFrame {

    public static EventBus evento = new EventBus();
    
    /**
     * Método constructor de clase Frm_MenuPrincipal
     */
    public Frm_MenuPrincipal() {
        initComponents();
        setLocationRelativeTo(null);
        Cañas cana = new Cañas();
        cana.GenerarLado();
        reproducirMusica("src/Musica/ozuna-caramelo-video-oficial.wav");
        
//   reproducirMusica("C:\\Users\\Acedo\\Documents\\Sergio\\Arquitectura\\PATOLLI\\Revision2\\InterfazArq_Equipo2\\src\\Musica\\ozuna-caramelo-video-oficial.wav");
    }
    
    /**
     * Método estático que reproduce música de fondo.
     * @param musicLocation 
     */
    public static void reproducirMusica(String musicLocation) {

        try {

            File musicpath = new File(musicLocation);
            if (musicpath.exists()) {
                AudioInputStream audioInput;

                audioInput = AudioSystem.getAudioInputStream(musicpath);
                Clip clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
                clip.loop(Clip.LOOP_CONTINUOUSLY);

            } else {
                System.out.println("No existe el archivo");
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        btnReglas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnCrearJuego = new javax.swing.JButton();
        btnContinuarPartida = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnReglas.setText("Reglas");
        btnReglas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReglasActionPerformed(evt);
            }
        });
        getContentPane().add(btnReglas, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, -1, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));

        btnCrearJuego.setText("Crear Juego");
        btnCrearJuego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearJuegoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 100, -1));

        btnContinuarPartida.setText("Entrar a partida");
        btnContinuarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContinuarPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinuarPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 140, -1));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 370, -1, -1));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 400));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OLA.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1433131660_planetarium_1.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 400));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 20, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReglasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReglasActionPerformed

        Frm_Reglas reglas = new Frm_Reglas();
        reglas.setVisible(true);
        this.setVisible(false);
//        this.dispose();


    }//GEN-LAST:event_btnReglasActionPerformed

    private void btnContinuarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarPartidaActionPerformed

        new Frm_EntrarPartida().setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_btnContinuarPartidaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        try {
            System.exit(WIDTH);
        } catch (Exception ex) {
        }

    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnCrearJuegoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearJuegoActionPerformed
        Frm_Configuracion config = new Frm_Configuracion();
        config.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCrearJuegoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuarPartida;
    private javax.swing.JButton btnCrearJuego;
    private javax.swing.JButton btnReglas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
