/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfazarq;

import ObjetoNegocio.Casilla;
import ObjetoNegocio.Ficha;
import ObjetoNegocio.Jugador;
import ObjetoNegocio.Partida;
import interfazarq.panle.Grapchisdemo;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.greenrobot.eventbus.Subscribe;

/**
 *
 * @author Manuel
 */
public class Frm_Juego extends javax.swing.JFrame {

    /**
     * Creates new form FrmJuego
     */
    Graphics g;
    JPanel PanelT;
    Partida partida;
    int Casillas;
    Grapchisdemo gdemo;

    public Frm_Juego(Partida p) {
        this();
        this.partida = p;
        this.Casillas = p.getNumCasillas();
        mostrarTablero(this.Casillas);
        iniciarlbl();

    }

    /**
     * Método constructor de clase Frm_Juego
     */
    public Frm_Juego() {
        initComponents();
        iniciarlbl();
        this.setLocationRelativeTo(null);
    }

    /**
     * Metodo para generar la combinacion de los dados
     */
    public void LanzarDados() {
        //caña1
        partida.getCañas()[0].GenerarLado();
        partida.getCañas()[1].GenerarLado();
        partida.getCañas()[2].GenerarLado();
        partida.getCañas()[3].GenerarLado();
        partida.getCañas()[4].GenerarLado();
        if (partida.getCañas()[0].getLado()) {
            lbl_dado1P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cana.png")));
        } else {
            lbl_dado1P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canaL.png")));
        }
        //caña2
        if (partida.getCañas()[1].getLado()) {
            lbl_dado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cana.png")));
        } else {
            lbl_dado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canaL.png")));
        }
        //caña3
        if (partida.getCañas()[2].getLado()) {
            lbl_dado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cana.png")));
        } else {
            lbl_dado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canaL.png")));
        }
        //caña4
        if (partida.getCañas()[3].getLado()) {
            lbl_dado4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cana.png")));
        } else {
            lbl_dado4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canaL.png")));
        }
        //caña5
        if (partida.getCañas()[4].getLado()) {
            lbl_dado5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cana.png")));
        } else {
            lbl_dado5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canaL.png")));
        }
    }

    /**
     * Método que inicializa labels.
     */
    public void iniciarlbl() {

        lbl_dado1P.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canaL.png")));
        lbl_dado2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canaL.png")));
        lbl_dado3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canaL.png")));
        lbl_dado4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canaL.png")));
        lbl_dado5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/canaL.png")));
    }

    /**
     * Método que muestra tablero.
     *
     * @param Casillas
     */
    public void mostrarTablero(int Casillas) {
        PanelT = new Grapchisdemo(Casillas);
        PanelT.setLocation(676, 92);
        PanelT.setSize(720, 720);
        PanelT.setVisible(true);
        PanelJuego.add(PanelT);
        g = PanelT.getGraphics();
    }

    /**
     * Método que determina movimiento y lo regresa como número
     *
     * @return
     */
    public int determinarMovimiento() {
        int movimiento = 0;
        for (int i = 0; i < partida.getCañas().length; i++) {
            if (partida.getCañas()[i].getLado()) {
                movimiento++;
            }
        }
        if (movimiento == 5) {
            movimiento = 10;
        }
        return movimiento;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelJuego = new javax.swing.JPanel();
        btn_TirarCañas = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        btnMenuPrincipal = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbl_dado1P = new javax.swing.JLabel();
        lbl_dado2 = new javax.swing.JLabel();
        lbl_dado3 = new javax.swing.JLabel();
        lbl_dado4 = new javax.swing.JLabel();
        lbl_dado5 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        lbl_Codigo = new javax.swing.JLabel();
        lbl_J1 = new javax.swing.JLabel();
        lbl_J2 = new javax.swing.JLabel();
        lbl_J3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lbl_J4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelJuego.setBackground(new java.awt.Color(53, 43, 49));

        btn_TirarCañas.setText("Tirar cañas");
        btn_TirarCañas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TirarCañasActionPerformed(evt);
            }
        });

        jButton2.setText("Apostar");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tablero");

        jButton7.setText("Paga para mover ficha");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        btnMenuPrincipal.setText("Menu Principal");
        btnMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPrincipalActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Codigo de partida");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("N° Jugadores: 4(num ejemplo) ");

        lbl_dado1P.setBackground(new java.awt.Color(255, 255, 255));
        lbl_dado1P.setForeground(new java.awt.Color(240, 240, 240));

        lbl_dado2.setText("jLabel1");

        lbl_dado3.setText("jLabel2");

        lbl_dado4.setText("jLabel3");

        lbl_dado5.setText("jLabel4");

        lbl_Codigo.setFont(new java.awt.Font("Yu Gothic UI", 3, 18)); // NOI18N
        lbl_Codigo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Codigo.setText("jLabel1");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbl_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_Codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        lbl_J1.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lbl_J1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_J1.setText("Jugador 1:");

        lbl_J2.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lbl_J2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_J2.setText("Jugador 2:");

        lbl_J3.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lbl_J3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_J3.setText("Jugador 3:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Cantidad minima de apostar: 50 (Num ejemplo)");

        lbl_J4.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        lbl_J4.setForeground(new java.awt.Color(255, 255, 255));
        lbl_J4.setText("Jugador 4:");

        javax.swing.GroupLayout PanelJuegoLayout = new javax.swing.GroupLayout(PanelJuego);
        PanelJuego.setLayout(PanelJuegoLayout);
        PanelJuegoLayout.setHorizontalGroup(
            PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJuegoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelJuegoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelJuegoLayout.createSequentialGroup()
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelJuegoLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_TirarCañas, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelJuegoLayout.createSequentialGroup()
                                .addComponent(lbl_dado1P, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_dado2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_dado3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_dado4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_dado5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelJuegoLayout.createSequentialGroup()
                        .addComponent(lbl_J1)
                        .addGap(23, 23, 23)
                        .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(PanelJuegoLayout.createSequentialGroup()
                                .addComponent(lbl_J2)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_J3)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_J4)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 817, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(124, 124, 124)
                .addComponent(jLabel12)
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelJuegoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(23, 23, 23))
            .addGroup(PanelJuegoLayout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(btnMenuPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelJuegoLayout.setVerticalGroup(
            PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelJuegoLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8))
                .addGap(11, 11, 11)
                .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_dado1P, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_dado2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_dado3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_dado4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_dado5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(btn_TirarCañas, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelJuegoLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(100, 100, 100)
                        .addGroup(PanelJuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_J1)
                            .addComponent(lbl_J2)
                            .addComponent(lbl_J3)
                            .addComponent(lbl_J4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                        .addComponent(btnMenuPrincipal))
                    .addGroup(PanelJuegoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addGap(17, 17, 17)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelJuego, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelJuego, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPrincipalActionPerformed

        Frm_MenuPrincipal menu = new Frm_MenuPrincipal();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuPrincipalActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btn_TirarCañasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TirarCañasActionPerformed

        try {

            this.LanzarDados();

            //por la lista de fichas del jugador 0(ejemplo por ahora ) se recorrera cada una
            for (int i = 0; i < partida.getListaJugadores()[0].getFichas().length; i++) {
                //ficha de la lista del jugador en la posicion 0 y la ficha esta en la posicion i
                Ficha f = partida.getListaJugadores()[0].getFichas()[i];
                //si verificarDentro es falso entonces se metera la ficha en el centro
                if (!VerificarDentro(f.getId(), partida.getListaJugadores()[0])) {

                    moverFicha(f, f.getPosicion() + this.determinarMovimiento());

                    int Posicion = partida.getListaJugadores()[0].getFichas()[i].getPosicion();
                    partida.getListaJugadores()[0].getFichas()[i].setPosicion(Posicion + determinarMovimiento());
                    System.out.println(Posicion + determinarMovimiento());

                    return;

                } else {

                    meterFichaMeta(f, this.determinarMovimiento());

                    if (this.determinarMovimiento() > 0) {
                        partida.getListaJugadores()[0].getFichas()[i].setPosicion(0);

                        return;
                    }
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }


    }//GEN-LAST:event_btn_TirarCañasActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * Este metodo verifica que la ficha este dentro de la casilla
     * @param Id
     * @param jugador
     * @return boolean
     */
    public boolean VerificarDentro(int Id, Jugador jugador) {
        //jugador dado
        Jugador j = jugador;
        //por las fichas dentro de la lista de fichas en jugador

        for (int i = 0; i < j.getFichas().length; i++) {
            if (j.getFichas()[i].getId() == Id) {
                Ficha f = j.getFichas()[i];
                if (f.getPosicion() == -1) {
                    //posicion diferene a 0
                    return true;
                } else {
                    return false;
                }
            }
        }
        //si el id dado es igual al id de la ficha y
        // y si la posicion es diferente de 0 entonces se manda un true    
        //no esta dentro
        return false;
    }
    
    /**
     * Método que mete ficha en meta
     * @param ficha
     * @param movimientos 
     */
    public void meterFichaMeta(Ficha ficha, int movimientos) {

        if (movimientos > 0) {
            Grapchisdemo g = new Grapchisdemo(Casillas);
            gdemo.setx(500 + gdemo.getx());
            gdemo.sety(199 + gdemo.gety());
            gdemo.repaint();
//            gdemo.meterFichaCentral(this.PanelT.getGraphics(), 1);
            Casilla[] c = partida.getTablero().getCasillas();
            this.partida.getTablero().getCasillas()[0].agregarFichaLista(ficha);

            //Cambiar estado de ficha(posicion)
            System.out.println(c.length);
        } else {
            JOptionPane.showMessageDialog(null, "No se alcanzo el minimo puntaje para entrar");
            return;
        }
    }
    
    /**
     * Método que mueve ficha
     * @param ficha
     * @param movimientos 
     */
    public void moverFicha(Ficha ficha, int movimientos) {

        if (movimientos > 0) {
            gdemo.setx(199);
            gdemo.sety(566);
            gdemo.AvanzarFicha(this.PanelT.getGraphics(), movimientos, 1);
            gdemo.repaint();
        }

    }
    
    /**
     * Metodo que establece partida
     * @param partida 
     */
    @Subscribe
    public void establecerPartida(Partida partida) {
        this.partida = partida;
        this.Casillas = partida.getNumCasillas();
        mostrarTablero(Casillas);
        gdemo = new Grapchisdemo(Casillas);
        lbl_Codigo.setText(Integer.toString(this.partida.getCodigo()));
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelJuego;
    private javax.swing.JButton btnMenuPrincipal;
    private javax.swing.JButton btn_TirarCañas;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lbl_Codigo;
    private javax.swing.JLabel lbl_J1;
    private javax.swing.JLabel lbl_J2;
    private javax.swing.JLabel lbl_J3;
    private javax.swing.JLabel lbl_J4;
    private javax.swing.JLabel lbl_dado1P;
    private javax.swing.JLabel lbl_dado2;
    private javax.swing.JLabel lbl_dado3;
    private javax.swing.JLabel lbl_dado4;
    private javax.swing.JLabel lbl_dado5;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
